-- P1 Access Control: identity, role scope, teams, and audit foundation.
-- REVIEW GATE: this migration is committed for review and is not applied by repository CI.

begin;

alter table public.app_user_roles
  add column if not exists company_id bigint,
  add column if not exists team_id bigint,
  add column if not exists salesperson_id bigint;

alter table public.app_user_roles
  drop constraint if exists app_user_roles_role_check;

alter table public.app_user_roles
  add constraint app_user_roles_role_check
  check (role in ('sales_rep', 'supervisor', 'manager', 'admin'));

alter table public.app_user_roles
  drop constraint if exists app_user_roles_scope_check;

alter table public.app_user_roles
  add constraint app_user_roles_scope_check
  check (
    (role = 'sales_rep' and company_id is not null and salesperson_id is not null)
    or (role = 'supervisor' and company_id is not null and team_id is not null)
    or role in ('manager', 'admin')
  );

create table if not exists public.sales_teams (
  team_id bigint primary key,
  team_name text not null check (length(btrim(team_name)) between 2 and 120),
  company_id bigint not null,
  supervisor_user_id uuid references auth.users(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null
);

create unique index if not exists sales_teams_one_active_team_per_supervisor
  on public.sales_teams(supervisor_user_id)
  where supervisor_user_id is not null and is_active = true;

create table if not exists public.sales_team_members (
  team_id bigint not null references public.sales_teams(team_id) on delete cascade,
  salesperson_id bigint not null,
  salesperson_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  primary key (team_id, salesperson_id)
);

create index if not exists sales_team_members_salesperson_idx
  on public.sales_team_members(salesperson_id)
  where is_active = true;

create table if not exists public.access_control_audit_log (
  event_id bigint generated by default as identity primary key,
  target_user_id uuid references auth.users(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  action_type text not null,
  previous_scope jsonb,
  new_scope jsonb,
  created_at timestamptz not null default now()
);

create index if not exists access_control_audit_log_target_created_idx
  on public.access_control_audit_log(target_user_id, created_at desc);

create or replace function public.current_access_profile()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_profile public.app_user_roles%rowtype;
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  select *
    into v_profile
  from public.app_user_roles
  where user_id = v_uid
    and is_active = true;

  if not found then
    raise exception 'ACCESS_PROFILE_UNAVAILABLE' using errcode = '42501';
  end if;

  if v_profile.role = 'sales_rep'
     and (v_profile.company_id is null or v_profile.salesperson_id is null) then
    raise exception 'INVALID_SALES_REP_SCOPE' using errcode = '42501';
  end if;

  if v_profile.role = 'supervisor'
     and (v_profile.company_id is null or v_profile.team_id is null) then
    raise exception 'INVALID_SUPERVISOR_SCOPE' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'user_id', v_profile.user_id,
    'display_name', v_profile.display_name,
    'role', v_profile.role,
    'is_active', v_profile.is_active,
    'company_id', v_profile.company_id,
    'team_id', v_profile.team_id,
    'salesperson_id', v_profile.salesperson_id,
    'can_view_executive', v_profile.role in ('manager', 'admin'),
    'can_manage_users', v_profile.role = 'admin'
  );
end;
$$;

revoke all on function public.current_access_profile() from public;
revoke all on function public.current_access_profile() from anon;
grant execute on function public.current_access_profile() to authenticated;

-- IAM tables are never browser-writable. Read policies/grants are added deliberately
-- in the later hardening migration after all scoped RPCs exist.
revoke all on table public.sales_teams from anon, authenticated;
revoke all on table public.sales_team_members from anon, authenticated;
revoke all on table public.access_control_audit_log from anon, authenticated;

commit;
